import { FC } from 'react';
import Head from 'next/head';
import { css } from '@emotion/react';
import SideBar from '@/components/organisms/SideBar';
import Footer from '@/components/organisms/Footer';

const Layout: FC = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={container}>
        <SideBar />
        <div>
          {children}
          <Footer />
        </div>
      </div>
    </div>
  );
};

const container = css`
  display: flex;
`;

export default Layout;
